# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:

    runs-on: ubuntu-latest
<<<<<<< HEAD
=======
    env:
      TOKEN: ${{ secrets.TOKEN }}
      GUILD_ID:  ${{ secrets.GUILD_ID}}
      STAGE: ${{ secrets.STAGE }}
      GENERAL_CHANNEL: ${{ secrets.GENERAL_CHANNEL }}
      BOT_COMMANDS_CHANNEL: ${{ secrets.BOT_COMMANDS_CHANNEL }}
      MEMBER_LOG_CHANNEL: ${{ secrets.MEMBER_LOG_CHANNEL }}
>>>>>>> 4cf773eb7630fd85ecf2728a9a4a3c753c4c9ea1
    strategy:
      matrix:
        node-version: [v16.13.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm start
